backend:
  name: github
  repo: Crew-Awesome/weekbox.site
  branch: main
  base_url: https://weekbox.immalloy.com
  auth_endpoint: api/decap/auth
  use_graphql: true
  squash_merges: true

publish_mode: editorial_workflow
collections:
  - name: featured
    label: Featured Curation
    files:
      - file: content/featured/curation.json
        label: Curation Rules
        name: rules
        fields:
          - label: Blocked Mod IDs
            name: blockedMods
            widget: list
            required: false
            field:
              label: Mod ID
              name: id
              widget: number
              value_type: int
